### ISSUE TITLE
score for draw instead of win

### ISSUE THREAD

**Issue by awetscherek** [skeeto/connect4#1]
I might misinterpret this, but shouldn't the score for a draw be added here instead?

https://github.com/skeeto/connect4/blob/ffab09edd594e7439eb2d1861a05209b6ca4268d/connect4.c#L380

**Comment by skeeto** [comment]
I believe you're right thanks! Though, oddly, I tried playing a few games 
with the fix, and I'm not sure if I can tell the difference. It's subtle, 
but undoubtedly more correct.
